using AvalonPizza.Server.Interfaces.Repositories;
using AvalonPizza.Server.Models;
using Dapper;
using Microsoft.Data.SqlClient;
using System.Data;

namespace AvalonPizza.Server.Repositories;

public class OrderRepository : IOrderRepository
{
    private readonly string _connectionString;

    public OrderRepository(IConfiguration configuration)
    {
        _connectionString = configuration.GetConnectionString("DefaultConnection")
            ?? throw new ArgumentNullException(nameof(configuration), "Connection string 'DefaultConnection' not found.");
    }

    /// <summary>
    /// Retrieves a fully hydrated order record, including its child toppings collection, from the database.
    /// Executes a single optimized round-trip leveraging multi-grid result streams.
    /// </summary>
    /// <param name="orderId">The unique target identifier of the order to look up.</param>
    /// <returns>
    /// A task representing the asynchronous read operation. Returns the populated <see cref="Order"/> 
    /// graph if found; otherwise, returns <see langword="null"/> if the record is missing or inactive.
    /// </returns>
    public async Task<Order?> GetOrderByIdAsync(int orderId)
    {
        using var connection = new SqlConnection(_connectionString);
        // By opening it once at the start "Explicitly", you keep the connection open for the entire
        // "session" of that method, which is slightly more efficient for multiple result sets.
        // you ensure the connection is pulled from the pool and stays active for both the Order and the Toppings retrieval.
        // This prevents "connection toggling."
        await connection.OpenAsync();

        using var reader = await connection.QueryMultipleAsync(
            "usp_Orders_GetById", new { Id = orderId }, commandType: CommandType.StoredProcedure
        );

        var order = await reader.ReadSingleOrDefaultAsync<Order>();

        // safety check provided by Dapper. It ensures you don't try to read from the result stream
        // if it has already been closed or exhausted, which prevents runtime crashes.
        if (order != null && !reader.IsConsumed)
        {
            var toppings = await reader.ReadAsync<Topping>();
            order.Toppings = toppings.ToList();
        }

        return order;
    }

    /// <summary>
    /// Persists a validated customer order and its associated toppings to the SQL Server database.
    /// Executes a single atomic round-trip transaction using a high-performance Table-Valued Parameter (TVP).
    /// </summary>
    /// <param name="order">The fully validated domain order model populated with server-verified pricing.</param>
    /// <returns>The unique identifier (<see cref="int"/>) generated by the database for the newly created order.</returns>
    /// <exception cref="System.Data.SqlClient.SqlException">Thrown when a database error occurs during insertion.</exception>
    public async Task<int> CreateOrderAsync(Order order)
    {
        // DataTable implements IDisposable however it can't be desposed of on in helper function
        // dispose of it to ensure that memory is freed up immediately
        using var toppingDataTable = CreateToppingDataTable(order.Toppings);

        var parameters = new DynamicParameters();
        parameters.Add("@CustomerName", order.CustomerName);
        parameters.Add("@PhoneNumber", order.PhoneNumber);
        parameters.Add("@DeliveryAddress", order.DeliveryAddress);
        parameters.Add("@SizeId", order.SizeId);
        parameters.Add("@TotalPrice", order.TotalPrice);
        parameters.Add("@Toppings", toppingDataTable.AsTableValuedParameter("dbo.ToppingListType"));

        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        return await connection.QuerySingleAsync<int>(
            "usp_Orders_Insert", parameters, commandType: CommandType.StoredProcedure
        );
    }

    /// <summary>
    /// Synchronizes changes to an existing order's configuration within the database.
    /// Passes updated components via a high-performance Table-Valued Parameter (TVP) 
    /// to update child junction details atomically.
    /// </summary>
    /// <param name="order">The updated order domain model containing target IDs, new size selection, and updated pricing.</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous database execution.</returns>
    /// <exception cref="System.Data.SqlClient.SqlException">
    /// Thrown if database side-validation rejects the modification (e.g., the order state is no longer 'Pending').
    /// </exception>
    public async Task UpdateOrderAsync(Order order)
    {
        using var toppingTable = CreateToppingDataTable(order.Toppings);

        var parameters = new DynamicParameters();
        parameters.Add("@OrderId", order.Id);
        parameters.Add("@SizeId", order.SizeId);
        parameters.Add("@TotalPrice", order.TotalPrice);
        parameters.Add("@Toppings", toppingTable.AsTableValuedParameter("dbo.ToppingListType"));

        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        await connection.ExecuteAsync(
            "usp_Orders_Update", parameters, commandType: CommandType.StoredProcedure
        );
    }

    /// <summary>
    /// Converts a collection of domain topping objects into a structured in-memory ADO.NET <see cref="DataTable"/>.
    /// The resulting schema matches the user-defined table type schema (<c>dbo.ToppingListType</c>) required by SQL Server.
    /// </summary>
    /// <param name="toppings">The collection of selected pizza toppings containing target identifiers.</param>
    /// <returns>A populated <see cref="DataTable"/> ready to be safely processed as a Table-Valued Parameter.</returns>
    private DataTable CreateToppingDataTable(IEnumerable<Topping> toppings)
    {
        var toppingsDataTable = new DataTable();
        toppingsDataTable.Columns.Add("ToppingId", typeof(int));

        if (toppings != null)
        {
            foreach (var topping in toppings)
            {
                toppingsDataTable.Rows.Add(topping.ToppingId);
            }
        }

        return toppingsDataTable;
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="orderId"></param>
    /// <param name="statusId"></param>
    /// <returns></returns>
    public async Task UpdateOrderStatusAsync(int orderId, int statusId)
    {
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        await connection.ExecuteAsync(
            "usp_Orders_UpdateStatus", new { OrderId = orderId, StatusId = statusId }, commandType: CommandType.StoredProcedure
        );
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="orderId"></param>
    /// <returns></returns>
    public async Task DeleteOrderAsync(int orderId)
    {
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        await connection.ExecuteAsync(
            "usp_Orders_Delete", new { OrderId = orderId }, commandType: CommandType.StoredProcedure
        );
    }
}